name: peloton
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+5

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: "^0.5.0"  
  cupertino_icons: ^0.1.2
  smooth_page_indicator: ^0.1.5
  provider: ^4.1.0-dev+1
  shared_preferences: ^0.5.7+1 
  flutter_svg: ^0.17.4
#  http: ^0.12.1
  intl_phone_number_input: ^0.4.5
  pinput: ^0.2.3
  firebase_auth: ^0.18.0+1
  flutter_email_sender: ^3.0.1
  cloud_firestore: ^0.14.3
  url_launcher: ^5.5.3
  sticky_headers: ^0.1.8+1
  fl_chart: ^0.10.0
  image_picker: ^0.6.7+2
  firebase_storage: ^4.0.0
  country_code_picker: ^1.4.0
  keyboard_visibility: ^0.5.6
  video_thumbnail: ^0.2.2
  path_provider: ^1.6.11
  video_player: ^0.10.12+5
  chewie: ^0.9.10

  flutter_datetime_picker: ^1.4.0
  photo_view: ^0.9.2
  icon_shadow: ^1.0.1
  cached_network_image: ^2.2.0+1
  firebase_messaging: ^7.0.0
  location: ^3.0.2
  flutter_pdfview: ^1.0.0+10
  pdf_flutter: ^1.1.3
  quickblox_sdk: ^0.3.8-alpha
  plain_notification_token: ^0.0.1
  connectivity: 0.4.4+1
  permission_handler: ^5.0.1+1
  firebase_analytics: ^6.0.2
  flutter_local_notifications: ^2.0.0+1
  charts_flutter: ^0.9.0
  geocoder: ^0.2.1
  package_info: ^0.4.3
  firebase_dynamic_links: ^0.6.2
  

  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - locale/localization_en.json
    - locale/localization_ar.json
    - locale/localization_he.json
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Inter
       fonts:
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-Regular.ttf
          weight: 500
      
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
